# fly.toml app configuration file generated for puppeteer-crawler on 2024-02-04T15:22:46+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'puppeteer-crawler'
primary_region = 'nrt'

[build]
  image = 'onurusluca/puppeteer-crawler:latest'

[deploy]

[env]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

[[services.ports]]
    port = 80
    handlers = ['http']

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
